# Generated by Django 5.2.16 on 2026-09-11 06:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0003_pipelinerun_process_all_patches"),
    ]

    operations = [
        migrations.AddField(
            model_name="pipelinerun",
            name="run_name",
            field=models.CharField(
                blank=True,
                default="",
                help_text="Optional human-readable name. Auto-generated if blank.",
                max_length=255,
            ),
        ),
    ]
