# Generated by Django 5.2.16 on 2026-09-18 17:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0004_pipelinerun_run_name"),
    ]

    operations = [
        migrations.AddField(
            model_name="pipelinerun",
            name="current_stage",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
