import React from "react";
import { motion } from "framer-motion";
import { useEffect, useState } from "react";
import { BarChart3, Image as ImageIcon, ChevronLeft, ChevronRight, ScanSearch, X } from "lucide-react";

const outputImages = [
  "15-11-20_16PCC_18.png",
  "14-9-18_16PCC_20.png",
  "14-11-18_48PZC_5.png",
  "12-12-20_16PCC_9.png",
  "12-12-20_16PCC_13.png",
  "30-8-18_16PCC_37.png",
  "18-5-19_51PTS_1.png",
  "16-2-18_16PEC_5.png",
  "30-8-18_16PCC_5.png",
  "4-3-18_50LLR_22.png",
];

const formatPercent = (value) => `${(value * 100).toFixed(1)}%`;

function Metric({ label, value, accent = "text-primary" }) {
  return (
    <div className="rounded-lg bg-muted/30 px-3 py-2.5">
      <p className="text-[10px] uppercase tracking-wider text-muted-foreground">{label}</p>
      <p className={`mt-1 text-lg font-semibold ${accent}`}>{value}</p>
    </div>
  );
}

function ScoreBar({ label, value, highlight = false }) {
  return (
    <div className="space-y-1.5">
      <div className="flex items-center justify-between gap-3 text-xs">
        <span className={`truncate ${highlight ? "font-semibold text-primary" : "text-muted-foreground"}`}>{label}</span>
        <span className="font-mono text-foreground">{formatPercent(value)}</span>
      </div>
      <div className="h-1.5 overflow-hidden rounded-full bg-muted">
        <div
          className={`h-full rounded-full ${highlight ? "bg-primary" : "bg-secondary/70"}`}
          style={{ width: `${Math.max(0, Math.min(value * 100, 100))}%` }}
        />
      </div>
    </div>
  );
}

const ModelPage = () => {
  const [selectedIndex, setSelectedIndex] = useState(0);
  const [isExpanded, setIsExpanded] = useState(false);
  const [evaluation, setEvaluation] = useState(null);
  const selectedImage = outputImages[selectedIndex];

  useEffect(() => {
    Promise.all([
      fetch("/asserts/segformer_eval_results/evaluation_results.json").then((response) => response.json()),
      fetch("/asserts/polymer/polymer_xgb_model_eval.json").then((response) => response.json()),
    ]).then(([segformer, polymer]) => {
      setEvaluation({ segformer, polymer });
    }).catch((error) => {
      console.error("Unable to load model evaluation results", error);
    });
  }, []);

  const selectPrevious = () => {
    setSelectedIndex((currentIndex) =>
      currentIndex === 0 ? outputImages.length - 1 : currentIndex - 1,
    );
  };

  const selectNext = () => {
    setSelectedIndex((currentIndex) => (currentIndex + 1) % outputImages.length);
  };

  return (
    <main className="min-h-screen bg-background pt-14">
      <div className="max-w-[1500px] mx-auto px-4 sm:px-6 py-6 sm:py-8">
        <motion.header
          initial={{ opacity: 0, y: 10 }}
          animate={{ opacity: 1, y: 0 }}
          className="mb-8"
        >
          <div className="flex items-center gap-3 mb-2">
            <div className="w-10 h-10 rounded-xl bg-primary/15 text-primary flex items-center justify-center">
              <ScanSearch className="w-5 h-5" />
            </div>
            <div>
              <h1 className="font-heading text-2xl font-bold">Model Performance</h1>
              <p className="text-sm text-muted-foreground">
                Visual results generated by the polymer detection model.
              </p>
            </div>
          </div>
        </motion.header>

        {evaluation && (
          <section aria-label="Model evaluation results" className="grid gap-5 lg:grid-cols-2 mb-8">
            <motion.article
              initial={{ opacity: 0, y: 12 }}
              animate={{ opacity: 1, y: 0 }}
              className="glass-card p-5"
            >
              <div className="flex items-center gap-2 mb-4">
                <BarChart3 className="w-4 h-4 text-primary" />
                <div>
                  <h2 className="font-heading font-semibold">SegFormer v2</h2>
                  <p className="text-xs text-muted-foreground">Segmentation evaluation</p>
                </div>
              </div>
              <div className="grid grid-cols-2 sm:grid-cols-3 gap-2 mb-5">
                <Metric label="Overall mIoU" value={formatPercent(evaluation.segformer.mIoU)} />
                <Metric label="Debris IoU" value={formatPercent(evaluation.segformer.debris_iou)} />
                <Metric label="Debris F1" value={formatPercent(evaluation.segformer.debris_f1)} />
                <Metric label="Precision" value={formatPercent(evaluation.segformer.debris_precision)} />
                <Metric label="Recall" value={formatPercent(evaluation.segformer.debris_recall)} />
              </div>
              <div className="space-y-3">
                <p className="text-xs font-semibold uppercase tracking-wider text-muted-foreground">Class IoU</p>
                {Object.entries(evaluation.segformer.per_class_iou).map(([label, value]) => (
                  <ScoreBar key={label} label={label} value={value} highlight={label === "Marine Debris"} />
                ))}
              </div>
            </motion.article>

            <motion.article
              initial={{ opacity: 0, y: 12 }}
              animate={{ opacity: 1, y: 0 }}
              transition={{ delay: 0.08 }}
              className="glass-card p-5"
            >
              <div className="flex items-center gap-2 mb-4">
                <BarChart3 className="w-4 h-4 text-secondary" />
                <div>
                  <h2 className="font-heading font-semibold">Polymer XGBoost</h2>
                  <p className="text-xs text-muted-foreground">Classification evaluation</p>
                </div>
              </div>
              <div className="grid grid-cols-2 sm:grid-cols-3 gap-2 mb-5">
                <Metric label="Accuracy" value={formatPercent(evaluation.polymer.accuracy)} accent="text-secondary" />
                <Metric label="Macro F1" value={formatPercent(evaluation.polymer["macro avg"]["f1-score"])} accent="text-secondary" />
                <Metric label="Weighted F1" value={formatPercent(evaluation.polymer["weighted avg"]["f1-score"])} accent="text-secondary" />
              </div>
              <div className="overflow-x-auto rounded-lg border border-border/30">
                <table className="w-full text-xs">
                  <thead className="bg-muted/30 text-muted-foreground">
                    <tr>
                      <th className="px-3 py-2 text-left font-medium">Class</th>
                      <th className="px-3 py-2 text-right font-medium">Precision</th>
                      <th className="px-3 py-2 text-right font-medium">Recall</th>
                      <th className="px-3 py-2 text-right font-medium">F1</th>
                    </tr>
                  </thead>
                  <tbody>
                    {Object.entries(evaluation.polymer)
                      .filter(([label, values]) => values && typeof values === "object" && values["f1-score"] !== undefined)
                      .map(([label, values]) => (
                        <tr key={label} className="border-t border-border/20">
                          <td className={`px-3 py-2 ${label === "Marine Debris" ? "font-semibold text-primary" : "text-muted-foreground"}`}>{label}</td>
                          <td className="px-3 py-2 text-right font-mono">{formatPercent(values.precision)}</td>
                          <td className="px-3 py-2 text-right font-mono">{formatPercent(values.recall)}</td>
                          <td className="px-3 py-2 text-right font-mono">{formatPercent(values["f1-score"])}</td>
                        </tr>
                      ))}
                  </tbody>
                </table>
              </div>
            </motion.article>
          </section>
        )}

        <section aria-label="Model output images" className="space-y-5">
          <div className="glass-card p-3">
            <div className="flex items-center justify-between px-2 pb-3">
              <span className="text-xs font-semibold uppercase tracking-wider text-muted-foreground">Outputs</span>
              <span className="text-xs text-muted-foreground">{selectedIndex + 1} / {outputImages.length}</span>
            </div>
            <div className="grid grid-cols-5 gap-2">
              {outputImages.map((filename, index) => (
                <button
                  key={filename}
                  type="button"
                  onClick={() => setSelectedIndex(index)}
                  className={`min-w-0 flex items-center justify-center gap-2 rounded-lg px-2.5 py-2 text-left text-xs transition-colors ${
                    selectedIndex === index
                      ? "bg-primary/15 text-primary border border-primary/25"
                      : "text-muted-foreground hover:bg-muted/50 hover:text-foreground border border-transparent"
                  }`}
                >
                  <ImageIcon className="w-4 h-4 shrink-0" />
                  <span className="font-mono truncate" title={`${index + 1}-vis-output`}>{index + 1}-vis-output</span>
                </button>
              ))}
            </div>
            <div className="flex gap-2 mt-3 pt-3 border-t border-border/30">
              <button type="button" onClick={selectPrevious} aria-label="Previous output" className="flex-1 flex justify-center rounded-lg py-2 text-muted-foreground hover:bg-muted/50 hover:text-foreground transition-colors">
                <ChevronLeft className="w-4 h-4" />
              </button>
              <button type="button" onClick={selectNext} aria-label="Next output" className="flex-1 flex justify-center rounded-lg py-2 text-muted-foreground hover:bg-muted/50 hover:text-foreground transition-colors">
                <ChevronRight className="w-4 h-4" />
              </button>
            </div>
          </div>

          <motion.figure
            key={selectedImage}
            initial={{ opacity: 0, x: 12 }}
            animate={{ opacity: 1, x: 0 }}
            className="glass-card overflow-hidden"
          >
            <button
              type="button"
              onClick={() => setIsExpanded(true)}
              className="block w-full cursor-zoom-in bg-muted/30"
              aria-label={`Enlarge ${selectedImage}`}
            >
              <img
                src={`/asserts/vis_output/${selectedImage}`}
                alt={`Model output ${selectedImage}`}
                className="w-full max-h-[70vh] object-contain"
              />
            </button>
            <figcaption className="flex items-center gap-2 px-4 py-3 text-xs text-muted-foreground">
              <ImageIcon className="w-4 h-4 text-primary shrink-0" />
              <span className="font-mono truncate" title={`${selectedIndex + 1}-vis-output`}>{selectedIndex + 1}-vis-output</span>
              <span className="ml-auto hidden sm:inline text-[10px]">Click image to enlarge</span>
            </figcaption>
          </motion.figure>
        </section>
      </div>

      {isExpanded && (
        <div
          role="dialog"
          aria-modal="true"
          aria-label={`Enlarged model output ${selectedImage}`}
          onClick={() => setIsExpanded(false)}
          className="fixed inset-0 z-[60] flex items-center justify-center bg-background/90 p-4 backdrop-blur-sm"
        >
          <button
            type="button"
            onClick={() => setIsExpanded(false)}
            aria-label="Close enlarged image"
            className="absolute right-4 top-4 rounded-lg p-2 text-muted-foreground hover:bg-muted/50 hover:text-foreground"
          >
            <X className="w-5 h-5" />
          </button>
          <img
            src={`/asserts/vis_output/${selectedImage}`}
            alt={`Enlarged model output ${selectedImage}`}
            onClick={(event) => event.stopPropagation()}
            className="max-h-[92vh] max-w-[96vw] object-contain"
          />
        </div>
      )}
    </main>
  );
};

export default ModelPage;