import React from "react";
import { motion } from "framer-motion";
import { useState } from "react";
import { Image as ImageIcon, ChevronLeft, ChevronRight, ScanSearch, X } from "lucide-react";

const outputImages = [
  "15-11-20_16PCC_18.png",
  "14-9-18_16PCC_20.png",
  "14-11-18_48PZC_5.png",
  "12-12-20_16PCC_9.png",
  "12-12-20_16PCC_13.png",
  "30-8-18_16PCC_37.png",
  "18-5-19_51PTS_1.png",
  "16-2-18_16PEC_5.png",
  "30-8-18_16PCC_5.png",
  "4-3-18_50LLR_22.png",
];

const ModelPage = () => {
  const [selectedIndex, setSelectedIndex] = useState(0);
  const [isExpanded, setIsExpanded] = useState(false);
  const selectedImage = outputImages[selectedIndex];

  const selectPrevious = () => {
    setSelectedIndex((currentIndex) =>
      currentIndex === 0 ? outputImages.length - 1 : currentIndex - 1,
    );
  };

  const selectNext = () => {
    setSelectedIndex((currentIndex) => (currentIndex + 1) % outputImages.length);
  };

  return (
    <main className="min-h-screen bg-background pt-14">
      <div className="max-w-[1500px] mx-auto px-4 sm:px-6 py-6 sm:py-8">
        <motion.header
          initial={{ opacity: 0, y: 10 }}
          animate={{ opacity: 1, y: 0 }}
          className="mb-8"
        >
          <div className="flex items-center gap-3 mb-2">
            <div className="w-10 h-10 rounded-xl bg-primary/15 text-primary flex items-center justify-center">
              <ScanSearch className="w-5 h-5" />
            </div>
            <div>
              <h1 className="font-heading text-2xl font-bold">Model Outputs</h1>
              <p className="text-sm text-muted-foreground">
                Visual results generated by the polymer detection model.
              </p>
            </div>
          </div>
        </motion.header>

        <section aria-label="Model output images" className="space-y-5">
          <div className="glass-card p-3">
            <div className="flex items-center justify-between px-2 pb-3">
              <span className="text-xs font-semibold uppercase tracking-wider text-muted-foreground">Outputs</span>
              <span className="text-xs text-muted-foreground">{selectedIndex + 1} / {outputImages.length}</span>
            </div>
            <div className="grid grid-cols-5 gap-2">
              {outputImages.map((filename, index) => (
                <button
                  key={filename}
                  type="button"
                  onClick={() => setSelectedIndex(index)}
                  className={`min-w-0 flex items-center justify-center gap-2 rounded-lg px-2.5 py-2 text-left text-xs transition-colors ${
                    selectedIndex === index
                      ? "bg-primary/15 text-primary border border-primary/25"
                      : "text-muted-foreground hover:bg-muted/50 hover:text-foreground border border-transparent"
                  }`}
                >
                  <ImageIcon className="w-4 h-4 shrink-0" />
                  <span className="font-mono truncate" title={`${index + 1}-vis-output`}>{index + 1}-vis-output</span>
                </button>
              ))}
            </div>
            <div className="flex gap-2 mt-3 pt-3 border-t border-border/30">
              <button type="button" onClick={selectPrevious} aria-label="Previous output" className="flex-1 flex justify-center rounded-lg py-2 text-muted-foreground hover:bg-muted/50 hover:text-foreground transition-colors">
                <ChevronLeft className="w-4 h-4" />
              </button>
              <button type="button" onClick={selectNext} aria-label="Next output" className="flex-1 flex justify-center rounded-lg py-2 text-muted-foreground hover:bg-muted/50 hover:text-foreground transition-colors">
                <ChevronRight className="w-4 h-4" />
              </button>
            </div>
          </div>

          <motion.figure
            key={selectedImage}
            initial={{ opacity: 0, x: 12 }}
            animate={{ opacity: 1, x: 0 }}
            className="glass-card overflow-hidden"
          >
            <button
              type="button"
              onClick={() => setIsExpanded(true)}
              className="block w-full cursor-zoom-in bg-muted/30"
              aria-label={`Enlarge ${selectedImage}`}
            >
              <img
                src={`/asserts/vis_output/${selectedImage}`}
                alt={`Model output ${selectedImage}`}
                className="w-full max-h-[70vh] object-contain"
              />
            </button>
            <figcaption className="flex items-center gap-2 px-4 py-3 text-xs text-muted-foreground">
              <ImageIcon className="w-4 h-4 text-primary shrink-0" />
              <span className="font-mono truncate" title={`${selectedIndex + 1}-vis-output`}>{selectedIndex + 1}-vis-output</span>
              <span className="ml-auto hidden sm:inline text-[10px]">Click image to enlarge</span>
            </figcaption>
          </motion.figure>
        </section>
      </div>

      {isExpanded && (
        <div
          role="dialog"
          aria-modal="true"
          aria-label={`Enlarged model output ${selectedImage}`}
          onClick={() => setIsExpanded(false)}
          className="fixed inset-0 z-[60] flex items-center justify-center bg-background/90 p-4 backdrop-blur-sm"
        >
          <button
            type="button"
            onClick={() => setIsExpanded(false)}
            aria-label="Close enlarged image"
            className="absolute right-4 top-4 rounded-lg p-2 text-muted-foreground hover:bg-muted/50 hover:text-foreground"
          >
            <X className="w-5 h-5" />
          </button>
          <img
            src={`/asserts/vis_output/${selectedImage}`}
            alt={`Enlarged model output ${selectedImage}`}
            onClick={(event) => event.stopPropagation()}
            className="max-h-[92vh] max-w-[96vw] object-contain"
          />
        </div>
      )}
    </main>
  );
};

export default ModelPage;